# Site
repository: hanscom95/about
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 문태훈
title: 개발자로 오래 살고 싶은 직딩
email: hanscom94@gmail.com
website: hanscom95.github.io

# Dark Mode (true/false/never) 
darkmode: false

# Social links
# twitter_username: facespics
github_username: hanscom95
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: "100002479598118"
# flickr_username: jekyll
instagram_username: moon_developer_93
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  일, 생활 모두 재미있게 하자! 커피를 좋아하고 여행을 좋아하는 직딩으로 개발자로 오래 먹고 살기 위해 노력해 나가는 중이다. 프론트 개발부터 앱 개발(안드로이드, 플로터), System 프로그래밍, 백엔드, DevOps까지 많은 걸 건드렸으나 아직 배고픈? 개발자다.

  I am most skilled in: <mark>Java</mark> and <mark>Node</mark> and <mark>Travel</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Gait Tracking App
        link: github.com/hanscom95/android/tree/main/standing_egg/Gait_BLE
        # link_text: Project Website
        additional_links:
          - title:  hanscom95/Gait_BLE
            icon: fab fa-github
            url: github.com/hanscom95/android/tree/main/standing_egg/Gait_BLE
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Gait Tracking Solution. 관성항법장치(Inertial Navigation System)를 바탕으로 한 걸음 위치추적 시스템
        description: | # this will include new lines to allow paragraphs
          GPS 여부 관계 없이 실내/실외 상황 모두에서 발걸음의 위치를 추적
          Standing-Egg에서 제작한 SGO100 EVK Black Board와 발걸음 Tracking 알고리즘을 암호화 code로 변환하여 BLE모듈과 wifi모듈을 통해 앱으로 전송 시키는 프로젝트
          Wifi는 udp, bluetooth는 BLE4.0 통신

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 주식회사 비스퀘어랩
        link: www.bsquarelab.com
        # link_text: bsquarelab.com
        sub_title: BlockChain, BackEnd System, DevOps
        caption: December 2020 - Present
        quote: >
          비스퀘어랩 Square Leisure 기반 DID, Data Governance, Cross-Chain Interoperability 및 Oracle과 같은 솔루션을 제공
        description: | # this will include new lines to allow paragraphs
            주로 백엔드 개발을 맡고 있으며 DevOps쪽 방향으로 스터디하며 개발 뎁스를 늘려가고 있다.
            주 사용 언어: Node, Go, Java, Dart, Objective-C, MYSQL
            주 사용 프레임워크: Flutter, Spring Boot, Android, iOS
            주 사용 플랫폼: Docker, AWS, Ubuntu, CentOS
      - layout: left
        title: 대한민국공군
        link: rokaf.airforce.mil.kr
        # link_text: artech.limited
        sub_title: 공군, 진주교육사령부
        caption:  February 2019 - December 2020
        quote: >
          공군에서 사용하는 AR, VR기반 교육훈련 콘텐츠 개발 Unreal을 사용, 주로 3D 게임 개발
        description: | # this will include new lines to allow paragraphs
          군대 보직 중 가장 개발일에 가깝다고 생각되는 것중 하나인 '교육훈련 매체개발병' 들어가 Unreal로 게임을 개발
          이곳은 처음부터 끝까지 병사들 위주로 게임이 개발되는데 3D max, 블랜더로 게임에 사용될 제작물을 만들고
          언리얼 엔진으로 3차원 게임을 개발한다. 복무중 개발한 프로젝트는 '기상관측 VR훈련 콘텐츠', '방공포대 패트리어트 3D 컨트롤 훈련', '항공기삭별 VR훈련 콘텐츠' 개발
          (군대에서 개발한것들은 군수품이라 못가지고 나온다 ㅜㅜ 그래도 만든 프로젝트 중에 기사화된 거 첨부 <http://www.shinailbo.co.kr/news/articleView.html?idxno=1187147>)
          * 진짜 병사들이 전부 개발하는 곳... 군무원 들어가서 개인 개발 하는것도 심각하게 생각해 보게 한다...
          주 사용 언어: Unreal, Blueprint, C++
      - layout: left
        title: (주)알텍
        link: www.artech.limited
        # link_text: artech.limited
        sub_title: 양궁,
        caption: November 2017 - November 2018
        quote: >
          양궁 점수 인식 시스템 개발, 오픈마켓
        description: | # this will include new lines to allow paragraphs
            카메라를 이용한 양궁 점수 인식 프로그램으로 카메라를 무선으로 연결한 Android장치를 이용하여 자동 점수 인식 프로그램을 개발하였다. 점수 인식 성공률은 10발당 90% 정도를 보였으며,
            Computer Vision을 딥러닝 기술을 C++로 개발하였으며 Android JNI를 이용한 VIEW 프로그램을 개발
            낚시 관련 오픈마켓 앱을 출시 Android native로 개발하였으며 백엔드는 PHP 및 Node로 제작(현재 서비스 종료)
            [세상의 모든 미끼:세미](https://apkpure.com/%EC%84%B8%EC%83%81%EC%97%90%EB%AA%A8%EB%93%A0%EB%AF%B8%EB%81%BC-%EC%84%B8%EB%AF%B8/artech.com.semi.free)
            주 사용 언어: Java, C++, PHP, Android, iOS, Node
      - layout: left
        title: 주식회사 스탠딩에그
        link: www.standing-egg.com
        # link_text: standing.com
        sub_title: Sensor Fusion 
        caption: May 2015 - November 2017
        quote: >
          Software programming with sensors
        description: | # this will include new lines to allow paragraphs
            Kalman filter, sensor fusion algorithm programming using 9-axis sensor. Android app development that links tracking, fitness, and iot systems.
            주 사용 언어: C++, Python, Java, Android
      - layout: left
        title: 씨앤토트플러스(주)
        link: www.cnthoth.com
        # link_text: cnthoth.com
        sub_title: SI, UI Framework, App
        caption: Oct 2011 - May 2015
        quote: >
          SI 아웃소싱 업체, 주로 SK계열사의 시스템을 개발 및 운영 서비스
        description: | # this will include new lines to allow paragraphs
          프론트엔드를 주로 개발하였으며 SKC&C 소속 자체 UI Framework를 만드는 팀에서 근무
          javascript를 기반으로 한 자체 UI 페이지를 개발, 프로젝트가 진행된 업체에 파견 SpringBoot, .Net, Android 등을 함께 개발
          주 사용 언어: Javascript, Java, Jquery

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INHA University
        caption: 2015 - 2019
        sub_title: 융합기술경영학부
        quote: >
          산업 전반에서 일어나는 복합적인 문제를 IT, 공학, 경영 등 여러 각도 에서 분석하고, 실제로 적용할 수 있는 융합적인 해결 방법을 찾아내는 능력을 기를 수 있도록 교육
        description: | # this will include new lines to allow paragraphs
          공과대학 융합기술경영학부 소속으로 4년 만기 졸업. 학기중 (주)스탠딩 에그 회사에 주임 연구원으로 재직(회사생활과 학교생활을 병행 하였다)
          고등학교 졸업후 개발자로 바로 취업을 해서 그런지 대학생활과 교육을 좀더 받고 싶었다.
          그래도 제대로된 개발일은 계속 하고 싶어 대학을 다니며 직장생활을 병행하게 해줄 회사를 찾아 이직 했다.(덕분에 주말은 포기ㅎㅎ)
          대학생활을 최대한 즐기려고 하였으나 이놈에 회사 생활은... 그래도 후회는 없다!(졸업 후 군대간 건 안비밀...)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      여행을 좋아하며 사진과 커피, 맛있는 음식과 술 한잔을 사랑하는 꿈많은 사람이 되고 싶은 개발자, 취미는:
      - 사진
      - 커피
      - 여행
      - 재밌는 술자리?

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

plugins:
 - jekyll-seo-tag

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed
